### ISSUE TITLE
Spoqa Hans Sans Neo 폰트 로드 이슈

### ISSUE THREAD

**Issue by donghhan** [study-group-portfolio/study-frontend#10]
1. Spoqa Hans Sans Neo의 폰트가 느리게 로드되거나
2. 가끔씩 아예 로드가 되지 않는 이슈가 있음

**Comment by donghhan** [comment]
```css
body {
    font-family: 'Spoqa Han Sans Neo', 'sans-serif';
}
```
를 하기와 같이 수정함 (단순 오타)

```css
body {
    font-family: 'Spoqa Han Sans Neo', sans-serif;
}
```
